version: '2'
services:
  web:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo/imagery-request
    env_file:
      - local.env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    image: mongo